@startuml updateRestaurantInfo&items

actor "Restaurant\nOwner" as Owner
participant "Home\nPage" as HomePage
participant "Update\nRestaurant\nScreen" as UpdateScreen
control "Restaurant\nController" as RestaurantController
database Database

Owner -> HomePage: open the app
HomePage -> UpdateScreen: click on update info/items button
UpdateScreen -> RestaurantController: update info/items

activate RestaurantController
RestaurantController -> RestaurantController: the controller\nprocess the request
UpdateScreen x-- RestaurantController: error
RestaurantController -> Database: \n  update restaurant in DB
deactivate RestaurantController

activate Database
Database -> Database: process request
RestaurantController x-- Database: update not saved
RestaurantController <-- Database: update saved
deactivate Database
UpdateScreen x-- RestaurantController : error
UpdateScreen <-- RestaurantController : successful update



@enduml