@startuml updateRegister

actor "Restaurant\nOwner" as Owner
participant "Home\nPage" as HomePage
participant "Update\nRestaurant\nScreen" as UpdateScreen
control "Restaurant\nController" as RestaurantController
database Database

Owner -> HomePage: open the app
HomePage -> UpdateScreen: click on update info button
UpdateScreen -> RestaurantController: update info

activate RestaurantController
RestaurantController -> RestaurantController: the controller\nprocess the request
UpdateScreen x-- RestaurantController: display error message and\n go back on update screen
RestaurantController -> Database: \n  update restaurant in DB
deactivate RestaurantController

activate Database
Database -> Database: process request
UpdateScreen x-- Database: show error related to DB
UpdateScreen <-- Database: successful update
deactivate Database



@enduml