@startuml dish
left to right direction
class Dish {
  -long id
  -String name
  -String description
  -DishCategory category
  -Restaurant restaurant
  -double price
  -List<String> allergens
  -List<String> ingredients
  --
  #Dish()
  #Dish(String username, String restaurant)
  #Dish(String name, Restaurant restaurant, 
  \t DishCategory category, double price)
  ..
  getters and setters
}

enum DishCategory{
    APPETIZER("Antipasto")
    FIRST("Primo")
    SECOND("Secondo")
    PIZZA("Pizza")
    DESSERT("Dolce")
    FRUITS("Frutta")
    BEERS("Birre")
    DRINKS("Bevande")
    WINE("Vini")
    -String displayValue
    --
    -DishCategory(String displayValue)
    +String getDisplayValue()
}

DishCategory *-- Dish
@enduml