@startuml Reservation
left to right direction
class Reservation {
  -long id
  -Customer customer
  -Restaurant restaurant
  -Map<Dish, Integer> dishesOrdered
  -LocalDateTime reservationDate
  -String displayValue
  --
  +Reservation {static} getFactory(String type)
  #Reservation()
  +getInvoiceTotalFee()
  ..
  getters and setters
}
@enduml