@startuml reservation
class Reservation {
  -long id
  -Customer customer
  -Restaurant restaurant
  -Map<Dish, Integer> dishesOrdered
  -PaymentMethod paymentMethod
  -LocalDateTime reservationDate
  --
  +Reservation()
  +double getInvoiceTotalFee()
  ..
  getters and setters
}

enum PaymentMethod {
    CASH("Contanti alla consegna")
    CREDITCARD("Carta di credito")
    PAYPAL("PayPal")
    -String displayValue
    --
    -PaymentMethod(String displayValue)
    +String getDisplayValue()
}

PaymentMethod *-- Reservation

@enduml