@startuml user
abstract class User {
  -long id
  -String username
  -String password
  -String name
  -String surname
  -String email
  -String telephoneNumber
  -Address address
  -Date birthdate
  --
  +User {static} getFactory(String type)
  #User()
  #User(String username, String password)
  ..
  getters and setters
}

class Customer {
    +Customer()
    +Customer(String username, String password)
}

class DeliveryMan {
    -boolean isAvailable
    +DeliveryMan()
    +DeliveryMan(String username, String password)
}

class RestaurantOwner {
    +RestaurantOwner()
    +RestaurantOwner(String username, String password)
}

hide Customer fields
hide RestaurantOwner fields

Customer <|-- User
DeliveryMan <|-- User
RestaurantOwner <|-- User

@enduml