@startuml login
scale 2
left to right direction
skinparam packageStyle rect
actor "user"
actor "deliveryman"
actor "restaurant"
rectangle  "application" {
    user -- (login) : if not logged
    user -- (logout) : if logged
    user -- (register) : if not logged
}
 
@enduml