@startuml useraccess
scale 2
left to right direction
skinparam packageStyle rect
actor "user"
rectangle "application" {
    user -- (register) : if not registered
    user -- (login) : if not\nalready\nlogged
    user -- (logout) : if logged
    user -- (view profile) : if logged
    user -- (view restaurants\nand available menu) : in any case
}

@enduml