@startuml displayrestaurants

actor User 
participant "Home\nPage" as HomePage
participant "Restaurant\nView" as RestaurantView
participant "Restaurant\nController" as RestaurantController
database Database as DB


User -> HomePage : open the app
HomePage -> RestaurantController: click on menu and choose\nreservation or order\nthen a restaurant category

activate RestaurantController
RestaurantController -> RestaurantController : the controller\nprocess the request
RestaurantController -> DB : the controller forwards\n the request to the DB
deactivate RestaurantController

RestaurantController <-- DB : retrieve a restaurants list\nof the chosen category from db
activate RestaurantController
RestaurantController -> RestaurantController : the controller\nprocess the data
HomePage x-- RestaurantController : go back to home\nand display error message\nif something goes wrong
RestaurantView <-- RestaurantController: finally display restaurants list\nto the User
deactivate RestaurantController
@enduml