@startuml Login Sequence Diagram

actor User
participant "Home\nPage" as HomePage
participant "Login\nScreen" as LoginScreen
control "User\nController" as UserController
database Database

User -> HomePage : open the app
HomePage -> LoginScreen : click on login button
LoginScreen -> UserController : insert username \nand password

activate UserController
UserController -> UserController: controller process the request
LoginScreen x-- UserController: \n  show error message
UserController -> Database : \n   check username\n   and password
deactivate UserController

LoginScreen x-- Database: validation failed 
HomePage <-- Database : validation successful:\nuser welcomed
@enduml
