@startuml Login Sequence Diagram

actor User
participant "Home\nPage" as HomePage
participant "Login\nScreen" as LoginScreen
control "User\nController" as UserController
database Database

User -> HomePage : open the app
HomePage -> LoginScreen : click on login button
LoginScreen -> UserController : insert username \nand password
UserController -> Database : username: found\npassword: match
LoginScreen x-- UserController : validation failed\n show error
HomePage <-- Database : validation successful:\nuser welcomed
@enduml
