@startuml register

actor User
participant "Home\nPage" as HomePage
participant "Registration\nScreen" as RegistrationScreen
participant "User\nController" as UserController
database Database

User -> HomePage: open the app
HomePage -> RegistrationScreen: click on register button
RegistrationScreen -> UserController: insert credentials
activate UserController
UserController -> UserController: the controller\nprocess the request
RegistrationScreen x-- UserController: display error message and\n  go back on registration screen
UserController -> Database: the controller inserts\n  user on DB
deactivate UserController
HomePage <-- Database: successful registration

@enduml